language: node_js
sudo: false
node_js:
   - "5.10.1"

before_script:
  - npm install -g npm@latest
  - npm install -g grunt
  - npm install -g grunt-cli

script: grunt check --verbose && grunt build  --verbose && grunt test --verbose


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3ccc58feb42775e3c408
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
